Temporarily disable site gen code coverage report
Cobertura site gen report fails on integration test:

DbUnitTaskIT.setUp:85->BuildFileTest.configureProject:235->
BuildFileTest.configureProject:248 ╗ NoSuchMethod

java.lang.NoSuchMethodError:
org.apache.tools.ant.util.FileUtils.
getFileUtils()Lorg/apache/tools/ant/util/FileUtils;
        at org.dbunit.ant.DbUnitTaskIT.setUp(DbUnitTaskIT.java:85)

Needs changing to Jacoco anyway...